export const componentNames: Record<string, string> = {
  "components-overview": "Overview",
  accordion: "Accordion",
  alert: "Alert",
  "alert-dialog": "Alert Dialog",
  "aspect-ratio": "Aspect Ratio",
  avatar: "Avatar",
  badge: "Badge",
  breadcrumb: "Breadcrumb",
  button: "Button",
  "button-group": "Button Group",
  calendar: "Calendar",
  card: "Card",
  carousel: "Carousel",
  chart: "Chart",
  checkbox: "Checkbox",
  collapsible: "Collapsible",
  command: "Command",
  "context-menu": "Context Menu",
  "date-picker": "Date Picker",
  dialog: "Dialog",
  drawer: "Drawer",
  "dotted-divider": "Dotted Divider",
  "dropdown-menu": "Dropdown Menu",
  empty: "Empty",
  field: "Field",
  filters: "Filters",
  frame: "Frame",
  input: "Input",
  "hover-card": "Hover Card",
  "input-group": "Input Group",
  "input-otp": "Input OTP",
  item: "Item",
  kbd: "Kbd",
  label: "Label",
  menubar: "Menubar",
  "native-select": "Native Select",
  "navigation-menu": "Navigation Menu",
  pagination: "Pagination",
  popover: "Popover",
  progress: "Progress",
  "radio-group": "Radio Group",
  resizable: "Resizable",
  "scroll-area": "Scroll Area",
  select: "Select",
  separator: "Separator",
  sheet: "Sheet",
  sidebar: "Sidebar",
  skeleton: "Skeleton",
  slider: "Slider",
  sonner: "Sonner",
  spinner: "Spinner",
  "unicode-spinner": "Unicode Spinner",
  "pixel-spinner": "Pixel Spinner",
  switch: "Switch",
  table: "Table",
  tabs: "Tabs",
  textarea: "Textarea",
  toggle: "Toggle",
  "toggle-group": "Toggle Group",
  tooltip: "Tooltip",
  typography: "Typography",
};
